### ISSUE TITLE
Does Not Run

### ISSUE THREAD

**Issue by lethargilistic** [BenWiederhake/PiWalkLn#1]
When I was translating this to use [(the far superior) e](https://github.com/lethargilistic/EWalkLn) instead of pi, I found that your program does not run directly after cloning it from GitHub. Perhaps you forgot to commit before pushing? Even if not, fixing it took me about 5 minutes, so it's no big deal.

**Comment by BenWiederhake** [comment]
Hell yeah! Nice adaption :D 

Also: I'm doing this because I want to learn the ways of Python, so thanks for the completely different way of fetching digits!

I'm going to fix the issues in a moment. Sorry, I'm kinda embarrassed that this slipped. I was coding the entire time in [bpython](https://github.com/bpython/bpython) and failed to notice the differences.

Can I add-in support e like you did? I'd add it as an argument to the `save_*` functions, I guess.

Finally: your image for "90°" links to `.../e_a1.35914_...`, which sounds a lot like it's actually the `pi/phi` angle, not 90° :P

**Comment by lethargilistic** [comment]
Regarding the angle, I wasn't really sure what the 1.359141 number was meant to indicate. I saw in the code that it was pi multiplied by a fraction such as 1.0/6 and that the result was `angle`, so I just replaced pi with e. So that angle is `e * (1/2)` ...Actually, now that I'm not programming at 3 AM, I'm remembering radians are a thing, so is that actually about 77 deg? That looks about right. I didn't need to purge pi completely, like I did. :laughing:

I could add support for e as a PR, but since you're learning it'd probably be a good exercise for you. My code is also public domain, so you can go right ahead and cull it.
